/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;

import java.awt.Color;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudip_Maiti
 */
public class Create_Emp extends javax.swing.JPanel {
String emp_Idcee;
String empcee;
 BigInteger emp_idcee =null;
    /**
     * Creates new form Create_Emp
     */
    public Create_Emp() {
        initComponents();
        id_createcee();
        
          fNamecee.setVisible(false);
        L_namecee.setVisible(false);
        Phonecee.setVisible(false);
        Emailcee.setVisible(false);
      
        mng_name.setEditable(false);
        mng_id.setEditable(false);
        Emp_idcee.setEditable(false);
         aaaacee.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fNamecee = new javax.swing.JLabel();
        Phonecee = new javax.swing.JLabel();
        Emailcee = new javax.swing.JLabel();
        crt_emp = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        L_namecee = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        aaaacee = new javax.swing.JLabel();
        firstnamecee = new javax.swing.JTextField();
        lastnamecee = new javax.swing.JTextField();
        emailcee = new javax.swing.JTextField();
        phone3cee = new javax.swing.JTextField();
        Emp_idcee = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresscee = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        mng_id = new javax.swing.JTextField();
        mng_name = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1122, 767));

        jPanel1.setBackground(new java.awt.Color(14, 73, 181));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.setMaximumSize(new java.awt.Dimension(1122, 765));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setText("Create New Employee !");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 30, 400, -1));

        fNamecee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fNamecee.setForeground(new java.awt.Color(128, 128, 128));
        fNamecee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fNamecee.setText("First Name");
        jPanel2.add(fNamecee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 20));

        Phonecee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Phonecee.setForeground(new java.awt.Color(128, 128, 128));
        Phonecee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Phonecee.setText("Phone");
        jPanel2.add(Phonecee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 20));

        Emailcee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Emailcee.setForeground(new java.awt.Color(128, 128, 128));
        Emailcee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Emailcee.setText("Email");
        jPanel2.add(Emailcee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 280, 20));

        crt_emp.setBackground(new java.awt.Color(0, 102, 255));
        crt_emp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Create Employee");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crt_empLayout = new javax.swing.GroupLayout(crt_emp);
        crt_emp.setLayout(crt_empLayout);
        crt_empLayout.setHorizontalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        crt_empLayout.setVerticalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(crt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 560, 50));

        L_namecee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        L_namecee.setForeground(new java.awt.Color(128, 128, 128));
        L_namecee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_namecee.setText("Last Name");
        jPanel2.add(L_namecee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 220, 20));

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(128, 128, 128));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Employee ID");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 20));

        aaaacee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        aaaacee.setForeground(new java.awt.Color(128, 128, 128));
        aaaacee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aaaacee.setText("Address");
        jPanel2.add(aaaacee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, 20));

        firstnamecee.setBackground(new java.awt.Color(255, 255, 255));
        firstnamecee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstnamecee.setForeground(new java.awt.Color(128, 128, 128));
        firstnamecee.setText("First Name");
        firstnamecee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        firstnamecee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameceeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameceeFocusLost(evt);
            }
        });
        firstnamecee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameceeActionPerformed(evt);
            }
        });
        jPanel2.add(firstnamecee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 30));

        lastnamecee.setBackground(new java.awt.Color(255, 255, 255));
        lastnamecee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lastnamecee.setForeground(new java.awt.Color(128, 128, 128));
        lastnamecee.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastnamecee.setText("Last Name");
        lastnamecee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        lastnamecee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameceeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameceeFocusLost(evt);
            }
        });
        lastnamecee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameceeActionPerformed(evt);
            }
        });
        jPanel2.add(lastnamecee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 280, 30));

        emailcee.setBackground(new java.awt.Color(255, 255, 255));
        emailcee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailcee.setForeground(new java.awt.Color(128, 128, 128));
        emailcee.setText("Email");
        emailcee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        emailcee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailceeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailceeFocusLost(evt);
            }
        });
        jPanel2.add(emailcee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 280, 30));

        phone3cee.setBackground(new java.awt.Color(255, 255, 255));
        phone3cee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        phone3cee.setForeground(new java.awt.Color(128, 128, 128));
        phone3cee.setText("Phone");
        phone3cee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        phone3cee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone3ceeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone3ceeFocusLost(evt);
            }
        });
        jPanel2.add(phone3cee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 30));

        Emp_idcee.setBackground(new java.awt.Color(255, 255, 255));
        Emp_idcee.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Emp_idcee.setForeground(new java.awt.Color(0, 0, 0));
        Emp_idcee.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Emp_idcee.setText("123456798");
        Emp_idcee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        Emp_idcee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_idceeActionPerformed(evt);
            }
        });
        jPanel2.add(Emp_idcee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 30));

        addresscee.setBackground(new java.awt.Color(255, 255, 255));
        addresscee.setColumns(10);
        addresscee.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addresscee.setForeground(new java.awt.Color(0, 0, 0));
        addresscee.setRows(5);
        addresscee.setText("Address");
        addresscee.setBorder(null);
        addresscee.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        addresscee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressceeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressceeFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(addresscee);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 560, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 600, 600));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Welcome !");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-group (3).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 440, 310));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("<Html> <p align = center>  CREATE  <br>   EMPLOYEE</p></Html>");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 440, 110));

        mng_id.setBackground(new java.awt.Color(14, 73, 181));
        mng_id.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        mng_id.setForeground(new java.awt.Color(255, 255, 255));
        mng_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mng_id.setToolTipText("");
        mng_id.setBorder(null);
        jPanel1.add(mng_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 290, 30));

        mng_name.setBackground(new java.awt.Color(14, 73, 181));
        mng_name.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        mng_name.setForeground(new java.awt.Color(255, 255, 255));
        mng_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mng_name.setToolTipText("");
        mng_name.setBorder(null);
        jPanel1.add(mng_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 void id_createcee(){
        Emp_idcee.setEditable(false);
         try{
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement("select * from id_store");         
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
              //  mng_Id=rs.getString("MNG_ID");
               // System.out.println("MANAGER ID "+mng_Id);
                emp_Idcee=rs.getString("emp_id");
              //  System.out.println("EMPLOYEE ID "+emp_Id);
              //  Transaction_Id=rs.getString("TRANSACTION_ID");
              //  System.out.println("Transaction_Id "+Transaction_Id);
             //   Product_id=rs.getString("PRODUCT_ID");
               
                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(null, "NOTHING FOUND IN DATABASE!!!!!!");
            }
            con.close();
           }
        catch(Exception e){System.out.println(e);}
         
        emp_idcee = new BigInteger(emp_Idcee);
        BigInteger nxt = new BigInteger("1");
      //  System.out.println("!!!!!!!!!!!!!!!!!!!!!!!!!!"+emp_Id);
      //  System.out.println("#################"+emp_id);
        emp_idcee = emp_idcee.add(nxt);
     //   System.out.println("%%%%%%%%%%%%%%%%%%%%%%"+emp_id);
        empcee = "ERP_E"+emp_idcee.toString();
    //    System.out.println("%%%%%%%%%%%%%%%%%%%%%%"+emp);
     //   System.out.println("++++++++++++++++"+emp_id);
        Emp_idcee.setText(empcee);
    }
    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        String fName = firstnamecee.getText();
        String lName = lastnamecee.getText();
        String ph = phone3cee.getText();
        String mail = emailcee.getText();

        String add = addresscee.getText();
        String empp=Emp_idcee.getText();

        if(fName.equals("First Name")||lName.equals("Last Name")||ph.equals("Phone")||mail.equals("Email")||add.equals("Address")||fName.equals("")||lName.equals("")||ph.equals("")||mail.equals("")||add.equals("")){
            // JOptionPane.showMessageDialog(this, "");
            new Warning("Fill up all field first").setVisible(true);
        }else{
            int i = ADD_NEW_EMP_DATAOBEJECT.create_emp(fName, lName, mail, ph,empp, add);

            int j = ID_STORE_FETCH.insert_id(emp_idcee.toString());
            if(i>0 || j>0){
                System.out.println("Data inserted");
                Succes su= new Succes();
                su.ot("Employee Created Succesfully");
                su.setVisible(true);

                firstnamecee.setText("");
                lastnamecee.setText("");
                phone3cee.setText("");
                emailcee.setText("");

                addresscee.setText("");

            }else{
                //  System.out.println("Data NOT inserted");
                new Error("Please Try Again!").setVisible(true);
            }

        }

    }//GEN-LAST:event_jLabel28MouseClicked

    private void firstnameceeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameceeFocusGained
        // TODO add your handling code here:
        if(firstnamecee.getText().equals("First Name")){
            fNamecee.setVisible(true);
            firstnamecee.setText("");
            firstnamecee.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_firstnameceeFocusGained

    private void firstnameceeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameceeFocusLost
        // TODO add your handling code here:
        if(firstnamecee.getText().equals("")){
            fNamecee.setVisible(false);
            firstnamecee.setText("First Name");
            firstnamecee.setForeground(new Color(128,128,128));
        }else{
            fNamecee.setVisible(true);
        }
    }//GEN-LAST:event_firstnameceeFocusLost

    private void firstnameceeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameceeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameceeActionPerformed

    private void lastnameceeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameceeFocusGained
        // TODO add your handling code here:
        if(lastnamecee.getText().equals("Last Name")){
            L_namecee.setVisible(true);
            lastnamecee.setText("");
            lastnamecee.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lastnameceeFocusGained

    private void lastnameceeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameceeFocusLost
        // TODO add your handling code here:
        if(lastnamecee.getText().equals("")){
            L_namecee.setVisible(false);
            lastnamecee.setText("Last Name");
            lastnamecee.setForeground(new Color(128,128,128));
        }else{
            L_namecee.setVisible(true);
        }
    }//GEN-LAST:event_lastnameceeFocusLost

    private void lastnameceeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameceeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameceeActionPerformed

    private void emailceeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailceeFocusGained
        // TODO add your handling code here:
        if(emailcee.getText().equals("Email")){
            Emailcee.setVisible(true);
            emailcee.setText("");
            emailcee.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_emailceeFocusGained

    private void emailceeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailceeFocusLost
        // TODO add your handling code here:
        if(emailcee.getText().equals("")){
            Emailcee.setVisible(false);
            emailcee.setText("Email");
            emailcee.setForeground(new Color(128,128,128));
        }else{
            Emailcee.setVisible(true);
        }
    }//GEN-LAST:event_emailceeFocusLost

    private void phone3ceeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3ceeFocusGained
        // TODO add your handling code here:
        if(phone3cee.getText().equals("Phone")){
            Phonecee.setVisible(true);
            phone3cee.setText("");
            phone3cee.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_phone3ceeFocusGained

    private void phone3ceeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3ceeFocusLost
        // TODO add your handling code here:
        if(phone3cee.getText().equals("")){
            Phonecee.setVisible(false);
            phone3cee.setText("Phone");
            phone3cee.setForeground(new Color(128,128,128));
        }else{
            Phonecee.setVisible(true);
        }
    }//GEN-LAST:event_phone3ceeFocusLost

    private void Emp_idceeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_idceeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_idceeActionPerformed

    private void addressceeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressceeFocusGained
        // TODO add your handling code here:
        if(addresscee.getText().equals("Address")){
            aaaacee.setVisible(true);
            addresscee.setText("");
            addresscee.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_addressceeFocusGained

    private void addressceeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressceeFocusLost
        // TODO add your handling code here:
        if(addresscee.getText().equals("")){
            aaaacee.setVisible(false);
            addresscee.setText("Address");
            addresscee.setForeground(new Color(128,128,128));
        }else{
            aaaacee.setVisible(true);
        }
    }//GEN-LAST:event_addressceeFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Emailcee;
    private javax.swing.JTextField Emp_idcee;
    private javax.swing.JLabel L_namecee;
    private javax.swing.JLabel Phonecee;
    private javax.swing.JLabel aaaacee;
    private javax.swing.JTextArea addresscee;
    private javax.swing.JPanel crt_emp;
    private javax.swing.JTextField emailcee;
    private javax.swing.JLabel fNamecee;
    private javax.swing.JTextField firstnamecee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnamecee;
    private javax.swing.JTextField mng_id;
    private javax.swing.JTextField mng_name;
    private javax.swing.JTextField phone3cee;
    // End of variables declaration//GEN-END:variables
}
