package erp;


import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sudip_Maiti
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        home.setVisible(true);
        ES.setVisible(false);
        CS.setVisible(false);
        Ws.setVisible(false);
        SM.setVisible(false);
        MP.setVisible(false);
       
        body7.setVisible(false);
        body8.setVisible(false);
        body9.setVisible(false);
        body10.setVisible(false);
        body11.setVisible(false);
        body12.setVisible(false);
        body13.setVisible(false);
        body13.setVisible(false);
        body14.setVisible(false);
        body15.setVisible(false);
       body16.setVisible(false);
        body17.setVisible(false);
        body18.setVisible(false);
       body19.setVisible(false);
        body20.setVisible(false);
//        home.setVisible(false);
//        home.setVisible(false);
//        home.setVisible(false);
//        home.setVisible(false);
//        home.setVisible(false);
//        home.setVisible(false);
                

        
        
    // this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
//frame.setUndecorated(true);
//frame.setVisible(true);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        a5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        p6 = new javax.swing.JPanel();
        a6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        p7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adn = new javax.swing.JLabel();
        adi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tt = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        dd1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        body = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        CS = new javax.swing.JPanel();
        ES = new javax.swing.JPanel();
        Ws = new javax.swing.JPanel();
        SM = new javax.swing.JPanel();
        MP = new javax.swing.JPanel();
        body7 = new javax.swing.JPanel();
        body8 = new javax.swing.JPanel();
        body9 = new javax.swing.JPanel();
        body10 = new javax.swing.JPanel();
        body11 = new javax.swing.JPanel();
        body24 = new javax.swing.JPanel();
        body22 = new javax.swing.JPanel();
        body23 = new javax.swing.JPanel();
        body21 = new javax.swing.JPanel();
        body14 = new javax.swing.JPanel();
        body15 = new javax.swing.JPanel();
        body18 = new javax.swing.JPanel();
        body19 = new javax.swing.JPanel();
        body17 = new javax.swing.JPanel();
        body20 = new javax.swing.JPanel();
        body13 = new javax.swing.JPanel();
        body16 = new javax.swing.JPanel();
        body12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 0)));

        menu.setBackground(new java.awt.Color(51, 51, 51));

        p1.setBackground(new java.awt.Color(51, 51, 51));
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
        });
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Home");
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 0, 175, 55));

        jLabel19.setText("jLabe");
        p1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 49, 55));

        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_rhombus_40px_1.png"))); // NOI18N
        p1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 0, 18, 55));

        p5.setBackground(new java.awt.Color(51, 51, 51));
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5MouseClicked(evt);
            }
        });
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a5.setForeground(new java.awt.Color(255, 255, 255));
        a5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_rhombus_40px_1.png"))); // NOI18N
        p5.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 0, 18, 55));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Stock Management");
        p5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 210, 55));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("jLabel17");
        p5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 51, 60));

        p3.setBackground(new java.awt.Color(51, 51, 51));
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3MouseClicked(evt);
            }
        });
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Employee Section");
        p3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 0, 234, 58));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("jLabel15");
        p3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 46, 58));

        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_rhombus_40px_1.png"))); // NOI18N
        p3.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 0, 18, 58));

        p4.setBackground(new java.awt.Color(51, 51, 51));
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4MouseClicked(evt);
            }
        });
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Working Section");
        p4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 190, 55));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("jLabel16");
        p4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 48, 55));

        a4.setForeground(new java.awt.Color(255, 255, 255));
        a4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_rhombus_40px_1.png"))); // NOI18N
        p4.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 0, 18, 55));

        p2.setBackground(new java.awt.Color(51, 51, 51));
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2MouseClicked(evt);
            }
        });
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Coustomer Section");
        p2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 220, 55));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel14");
        p2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 48, 55));

        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_rhombus_40px_1.png"))); // NOI18N
        p2.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 0, 18, 57));

        p6.setBackground(new java.awt.Color(51, 51, 51));
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6MouseClicked(evt);
            }
        });
        p6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a6.setForeground(new java.awt.Color(255, 255, 255));
        a6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_rhombus_40px_1.png"))); // NOI18N
        p6.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 0, 18, -1));

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Manage Password");
        p6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 210, 55));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("jLabel18");
        p6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 53, 52));

        p7.setBackground(new java.awt.Color(51, 51, 51));
        p7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p7MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Logout");

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(p1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        head.setBackground(new java.awt.Color(51, 51, 51));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_user_40px_2.png"))); // NOI18N
        head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 60, 55));

        adn.setForeground(new java.awt.Color(255, 255, 255));
        adn.setText("jLabel2");
        head.add(adn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 115, 25));

        adi.setForeground(new java.awt.Color(255, 255, 255));
        adi.setText("jLabel2");
        head.add(adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, 115, 25));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        head.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 10, -1, 30));

        tt.setForeground(new java.awt.Color(255, 255, 255));
        tt.setText("jLabel2");
        head.add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 70, 25));

        dd.setForeground(new java.awt.Color(255, 255, 255));
        dd.setText("jLabel2");
        head.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 40, 25));

        dd1.setForeground(new java.awt.Color(255, 255, 255));
        dd1.setText("jLabel2");
        head.add(dd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 60, 25));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        head.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 10, 30));

        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        CS.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout CSLayout = new javax.swing.GroupLayout(CS);
        CS.setLayout(CSLayout);
        CSLayout.setHorizontalGroup(
            CSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        CSLayout.setVerticalGroup(
            CSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(CS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        ES.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout ESLayout = new javax.swing.GroupLayout(ES);
        ES.setLayout(ESLayout);
        ESLayout.setHorizontalGroup(
            ESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        ESLayout.setVerticalGroup(
            ESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(ES, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        Ws.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout WsLayout = new javax.swing.GroupLayout(Ws);
        Ws.setLayout(WsLayout);
        WsLayout.setHorizontalGroup(
            WsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        WsLayout.setVerticalGroup(
            WsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(Ws, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        SM.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout SMLayout = new javax.swing.GroupLayout(SM);
        SM.setLayout(SMLayout);
        SMLayout.setHorizontalGroup(
            SMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        SMLayout.setVerticalGroup(
            SMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(SM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        MP.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout MPLayout = new javax.swing.GroupLayout(MP);
        MP.setLayout(MPLayout);
        MPLayout.setHorizontalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        MPLayout.setVerticalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body7.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body7Layout = new javax.swing.GroupLayout(body7);
        body7.setLayout(body7Layout);
        body7Layout.setHorizontalGroup(
            body7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body7Layout.setVerticalGroup(
            body7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body8.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body8Layout = new javax.swing.GroupLayout(body8);
        body8.setLayout(body8Layout);
        body8Layout.setHorizontalGroup(
            body8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body8Layout.setVerticalGroup(
            body8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body9.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout body9Layout = new javax.swing.GroupLayout(body9);
        body9.setLayout(body9Layout);
        body9Layout.setHorizontalGroup(
            body9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body9Layout.setVerticalGroup(
            body9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body10.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout body10Layout = new javax.swing.GroupLayout(body10);
        body10.setLayout(body10Layout);
        body10Layout.setHorizontalGroup(
            body10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body10Layout.setVerticalGroup(
            body10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body11.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body11Layout = new javax.swing.GroupLayout(body11);
        body11.setLayout(body11Layout);
        body11Layout.setHorizontalGroup(
            body11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body11Layout.setVerticalGroup(
            body11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body24.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body24Layout = new javax.swing.GroupLayout(body24);
        body24.setLayout(body24Layout);
        body24Layout.setHorizontalGroup(
            body24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body24Layout.setVerticalGroup(
            body24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body22.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout body22Layout = new javax.swing.GroupLayout(body22);
        body22.setLayout(body22Layout);
        body22Layout.setHorizontalGroup(
            body22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body22Layout.setVerticalGroup(
            body22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body23.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body23Layout = new javax.swing.GroupLayout(body23);
        body23.setLayout(body23Layout);
        body23Layout.setHorizontalGroup(
            body23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body23Layout.setVerticalGroup(
            body23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body21.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout body21Layout = new javax.swing.GroupLayout(body21);
        body21.setLayout(body21Layout);
        body21Layout.setHorizontalGroup(
            body21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body21Layout.setVerticalGroup(
            body21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body14.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout body14Layout = new javax.swing.GroupLayout(body14);
        body14.setLayout(body14Layout);
        body14Layout.setHorizontalGroup(
            body14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body14Layout.setVerticalGroup(
            body14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body15.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body15Layout = new javax.swing.GroupLayout(body15);
        body15.setLayout(body15Layout);
        body15Layout.setHorizontalGroup(
            body15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body15Layout.setVerticalGroup(
            body15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body18.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout body18Layout = new javax.swing.GroupLayout(body18);
        body18.setLayout(body18Layout);
        body18Layout.setHorizontalGroup(
            body18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body18Layout.setVerticalGroup(
            body18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body19.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body19Layout = new javax.swing.GroupLayout(body19);
        body19.setLayout(body19Layout);
        body19Layout.setHorizontalGroup(
            body19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body19Layout.setVerticalGroup(
            body19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body17.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout body17Layout = new javax.swing.GroupLayout(body17);
        body17.setLayout(body17Layout);
        body17Layout.setHorizontalGroup(
            body17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body17Layout.setVerticalGroup(
            body17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body20.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body20Layout = new javax.swing.GroupLayout(body20);
        body20.setLayout(body20Layout);
        body20Layout.setHorizontalGroup(
            body20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body20Layout.setVerticalGroup(
            body20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body13.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout body13Layout = new javax.swing.GroupLayout(body13);
        body13.setLayout(body13Layout);
        body13Layout.setHorizontalGroup(
            body13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body13Layout.setVerticalGroup(
            body13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body16.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body16Layout = new javax.swing.GroupLayout(body16);
        body16.setLayout(body16Layout);
        body16Layout.setHorizontalGroup(
            body16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body16Layout.setVerticalGroup(
            body16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        body12.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout body12Layout = new javax.swing.GroupLayout(body12);
        body12.setLayout(body12Layout);
        body12Layout.setHorizontalGroup(
            body12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        body12Layout.setVerticalGroup(
            body12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );

        body.add(body12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(1510, 866));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
        // TODO add your handling code here:
         home.setVisible(true);
        ES.setVisible(false);
        CS.setVisible(false);
        Ws.setVisible(false);
        SM.setVisible(false);
        MP.setVisible(false);
        a1.setVisible(true);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);

        body7.setVisible(false);
        body8.setVisible(false);
        body9.setVisible(false);
        body10.setVisible(false);
        body11.setVisible(false);
        body12.setVisible(false);
        body13.setVisible(false);
        body13.setVisible(false);
        body14.setVisible(false);
        body15.setVisible(false);
        body16.setVisible(false);
        body17.setVisible(false);
        body18.setVisible(false);
        body19.setVisible(false);
        body20.setVisible(false);
        p1.setBackground(Color.decode("#595260"));
        p2.setBackground(Color.decode("#333333"));
        p3.setBackground(Color.decode("#333333"));
        p4.setBackground(Color.decode("#333333"));
        p5.setBackground(Color.decode("#333333"));
        p6.setBackground(Color.decode("#333333"));
        p7.setBackground(Color.decode("#333333"));
        
    }//GEN-LAST:event_p1MouseClicked

    private void p2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseClicked
        // TODO add your handling code here:
         a2.setVisible(true);
        a1.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        p2.setBackground(Color.decode("#595260"));
        p1.setBackground(Color.decode("#333333"));
        p3.setBackground(Color.decode("#333333"));
        p4.setBackground(Color.decode("#333333"));
        p5.setBackground(Color.decode("#333333"));
        p6.setBackground(Color.decode("#333333"));
        p7.setBackground(Color.decode("#333333"));
        
        home.setVisible(false);
        ES.setVisible(false);
        CS.setVisible(true);
        Ws.setVisible(false);
        SM.setVisible(false);
        MP.setVisible(false);
       
        body7.setVisible(false);
        body8.setVisible(false);
        body9.setVisible(false);
        body10.setVisible(false);
        body11.setVisible(false);
        body12.setVisible(false);
        body13.setVisible(false);
        body13.setVisible(false);
        body14.setVisible(false);
        body15.setVisible(false);
       body16.setVisible(false);
        body17.setVisible(false);
        body18.setVisible(false);
       body19.setVisible(false);
        body20.setVisible(false);
    }//GEN-LAST:event_p2MouseClicked

    private void p3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseClicked
        // TODO add your handling code here:
        a3.setVisible(true);
        a2.setVisible(false);
        a1.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        p3.setBackground(Color.decode("#595260"));
        p2.setBackground(Color.decode("#333333"));
        p1.setBackground(Color.decode("#333333"));
        p4.setBackground(Color.decode("#333333"));
        p5.setBackground(Color.decode("#333333"));
        p6.setBackground(Color.decode("#333333"));
        p7.setBackground(Color.decode("#333333"));
        
        home.setVisible(false);
        ES.setVisible(true);
        CS.setVisible(false);
        Ws.setVisible(false);
        SM.setVisible(false);
        MP.setVisible(false);
       
        body7.setVisible(false);
        body8.setVisible(false);
        body9.setVisible(false);
        body10.setVisible(false);
        body11.setVisible(false);
        body12.setVisible(false);
        body13.setVisible(false);
        body13.setVisible(false);
        body14.setVisible(false);
        body15.setVisible(false);
       body16.setVisible(false);
        body17.setVisible(false);
        body18.setVisible(false);
       body19.setVisible(false);
        body20.setVisible(false);
    }//GEN-LAST:event_p3MouseClicked

    private void p4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseClicked
        // TODO add your handling code here:
        a4.setVisible(true);
        a2.setVisible(false);
        a3.setVisible(false);
        a1.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        p4.setBackground(Color.decode("#595260"));
        p2.setBackground(Color.decode("#333333"));
        p3.setBackground(Color.decode("#333333"));
        p1.setBackground(Color.decode("#333333"));
        p5.setBackground(Color.decode("#333333"));
        p6.setBackground(Color.decode("#333333"));
        p7.setBackground(Color.decode("#333333"));
         home.setVisible(false);
        ES.setVisible(false);
        CS.setVisible(false);
        Ws.setVisible(true);
        SM.setVisible(false);
        MP.setVisible(false);
       
        body7.setVisible(false);
        body8.setVisible(false);
        body9.setVisible(false);
        body10.setVisible(false);
        body11.setVisible(false);
        body12.setVisible(false);
        body13.setVisible(false);
        body13.setVisible(false);
        body14.setVisible(false);
        body15.setVisible(false);
       body16.setVisible(false);
        body17.setVisible(false);
        body18.setVisible(false);
       body19.setVisible(false);
        body20.setVisible(false);
    }//GEN-LAST:event_p4MouseClicked

    private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
        // TODO add your handling code here:
        a5.setVisible(true);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a1.setVisible(false);
        a6.setVisible(false);
        p5.setBackground(Color.decode("#595260"));
        p2.setBackground(Color.decode("#333333"));
        p3.setBackground(Color.decode("#333333"));
        p4.setBackground(Color.decode("#333333"));
        p1.setBackground(Color.decode("#333333"));
        p6.setBackground(Color.decode("#333333"));
        p7.setBackground(Color.decode("#333333"));
        home.setVisible(false);
        ES.setVisible(false);
        CS.setVisible(false);
        Ws.setVisible(false);
        SM.setVisible(true);
        MP.setVisible(false);
       
        body7.setVisible(false);
        body8.setVisible(false);
        body9.setVisible(false);
        body10.setVisible(false);
        body11.setVisible(false);
        body12.setVisible(false);
        body13.setVisible(false);
        body13.setVisible(false);
        body14.setVisible(false);
        body15.setVisible(false);
       body16.setVisible(false);
        body17.setVisible(false);
        body18.setVisible(false);
       body19.setVisible(false);
        body20.setVisible(false);
    }//GEN-LAST:event_p5MouseClicked

    private void p6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseClicked
        // TODO add your handling code here:
        a6.setVisible(true);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a1.setVisible(false);
        p6.setBackground(Color.decode("#595260"));
        p2.setBackground(Color.decode("#333333"));
        p3.setBackground(Color.decode("#333333"));
        p4.setBackground(Color.decode("#333333"));
        p5.setBackground(Color.decode("#333333"));
        p1.setBackground(Color.decode("#333333"));
        p7.setBackground(Color.decode("#333333"));
         home.setVisible(false);
        ES.setVisible(false);
        CS.setVisible(false);
        Ws.setVisible(false);
        SM.setVisible(false);
        MP.setVisible(true);
        body7.setVisible(false);
        body8.setVisible(false);
        body9.setVisible(false);
        body10.setVisible(false);
        body11.setVisible(false);
        body12.setVisible(false);
        body13.setVisible(false);
        body13.setVisible(false);
        body14.setVisible(false);
        body15.setVisible(false);
       body16.setVisible(false);
        body17.setVisible(false);
        body18.setVisible(false);
       body19.setVisible(false);
        body20.setVisible(false);
    }//GEN-LAST:event_p6MouseClicked

    private void p7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseClicked
        // TODO add your handling code here:
        a1.setVisible(true);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        p7.setBackground(Color.decode("#595260"));
        p2.setBackground(Color.decode("#333333"));
        p3.setBackground(Color.decode("#333333"));
        p4.setBackground(Color.decode("#333333"));
        p5.setBackground(Color.decode("#333333"));
        p6.setBackground(Color.decode("#333333"));
        p1.setBackground(Color.decode("#333333"));
         home.setVisible(true);
        ES.setVisible(false);
        CS.setVisible(false);
        Ws.setVisible(false);
        SM.setVisible(false);
        MP.setVisible(false);
        body7.setVisible(false);
        body8.setVisible(false);
        body9.setVisible(false);
        body10.setVisible(false);
        body11.setVisible(false);
        body12.setVisible(false);
        body13.setVisible(false);
        body13.setVisible(false);
        body14.setVisible(false);
        body15.setVisible(false);
       body16.setVisible(false);
        body17.setVisible(false);
        body18.setVisible(false);
       body19.setVisible(false);
        body20.setVisible(false);
    }//GEN-LAST:event_p7MouseClicked

                         

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CS;
    private javax.swing.JPanel ES;
    private javax.swing.JPanel MP;
    private javax.swing.JPanel SM;
    private javax.swing.JPanel Ws;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel adi;
    private javax.swing.JLabel adn;
    private javax.swing.JPanel body;
    private javax.swing.JPanel body10;
    private javax.swing.JPanel body11;
    private javax.swing.JPanel body12;
    private javax.swing.JPanel body13;
    private javax.swing.JPanel body14;
    private javax.swing.JPanel body15;
    private javax.swing.JPanel body16;
    private javax.swing.JPanel body17;
    private javax.swing.JPanel body18;
    private javax.swing.JPanel body19;
    private javax.swing.JPanel body20;
    private javax.swing.JPanel body21;
    private javax.swing.JPanel body22;
    private javax.swing.JPanel body23;
    private javax.swing.JPanel body24;
    private javax.swing.JPanel body7;
    private javax.swing.JPanel body8;
    private javax.swing.JPanel body9;
    private javax.swing.JLabel dd;
    private javax.swing.JLabel dd1;
    private javax.swing.JPanel head;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JLabel tt;
    // End of variables declaration//GEN-END:variables
}
