/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudip_Maiti
 */
public class Update_Emp extends javax.swing.JPanel {
 String Eppuepp="";
    public void emp_uepp(String ee){
        Eppuepp=ee;
    }
    /**
     * Creates new form Update_Emp
     */
    public Update_Emp() {
        initComponents();
        
        
         fNameuepp.setVisible(false);
        L_nameuepp.setVisible(false);
        Phoneuepp.setVisible(false);
        Emailuepp.setVisible(false);
       aaaauepp.setVisible(false);
       
        Emp_iduepp.setEditable(false);
        
        
        
        
        fName1uepp.setVisible(false);
        //System.out.println("empp"+Epp);
        if(Eppuepp!=""){
        updateuepp();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fNameuepp = new javax.swing.JLabel();
        Phoneuepp = new javax.swing.JLabel();
        Emailuepp = new javax.swing.JLabel();
        crt_emp = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        L_nameuepp = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        aaaauepp = new javax.swing.JLabel();
        firstnameuepp = new javax.swing.JTextField();
        lastnameuepp = new javax.swing.JTextField();
        emailuepp = new javax.swing.JTextField();
        phone3uepp = new javax.swing.JTextField();
        Emp_iduepp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressuepp = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        serchuepp = new javax.swing.JTextField();
        fName1uepp = new javax.swing.JLabel();
        jLabel2uepp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(14, 73, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fNameuepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fNameuepp.setForeground(new java.awt.Color(128, 128, 128));
        fNameuepp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fNameuepp.setText("First Name");
        jPanel2.add(fNameuepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 20));

        Phoneuepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Phoneuepp.setForeground(new java.awt.Color(128, 128, 128));
        Phoneuepp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Phoneuepp.setText("Phone");
        jPanel2.add(Phoneuepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 20));

        Emailuepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Emailuepp.setForeground(new java.awt.Color(128, 128, 128));
        Emailuepp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Emailuepp.setText("Email");
        jPanel2.add(Emailuepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 280, 20));

        crt_emp.setBackground(new java.awt.Color(0, 102, 255));
        crt_emp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Update");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crt_empLayout = new javax.swing.GroupLayout(crt_emp);
        crt_emp.setLayout(crt_empLayout);
        crt_empLayout.setHorizontalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
        crt_empLayout.setVerticalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(crt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 550, 50));

        L_nameuepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        L_nameuepp.setForeground(new java.awt.Color(128, 128, 128));
        L_nameuepp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_nameuepp.setText("Last Name");
        jPanel2.add(L_nameuepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 220, 20));

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(128, 128, 128));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Employee ID");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 20));

        aaaauepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        aaaauepp.setForeground(new java.awt.Color(128, 128, 128));
        aaaauepp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aaaauepp.setText("Address");
        jPanel2.add(aaaauepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, 20));

        firstnameuepp.setBackground(new java.awt.Color(255, 255, 255));
        firstnameuepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstnameuepp.setForeground(new java.awt.Color(128, 128, 128));
        firstnameuepp.setText("First Name");
        firstnameuepp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        firstnameuepp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameueppFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameueppFocusLost(evt);
            }
        });
        jPanel2.add(firstnameuepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 30));

        lastnameuepp.setBackground(new java.awt.Color(255, 255, 255));
        lastnameuepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lastnameuepp.setForeground(new java.awt.Color(128, 128, 128));
        lastnameuepp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastnameuepp.setText("Last Name");
        lastnameuepp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        lastnameuepp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameueppFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameueppFocusLost(evt);
            }
        });
        lastnameuepp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameueppActionPerformed(evt);
            }
        });
        jPanel2.add(lastnameuepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 280, 30));

        emailuepp.setBackground(new java.awt.Color(255, 255, 255));
        emailuepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailuepp.setForeground(new java.awt.Color(128, 128, 128));
        emailuepp.setText("Email");
        emailuepp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        emailuepp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailueppFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailueppFocusLost(evt);
            }
        });
        jPanel2.add(emailuepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 280, 30));

        phone3uepp.setBackground(new java.awt.Color(255, 255, 255));
        phone3uepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        phone3uepp.setForeground(new java.awt.Color(128, 128, 128));
        phone3uepp.setText("Phone");
        phone3uepp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        phone3uepp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone3ueppFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone3ueppFocusLost(evt);
            }
        });
        jPanel2.add(phone3uepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 30));

        Emp_iduepp.setBackground(new java.awt.Color(255, 255, 255));
        Emp_iduepp.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Emp_iduepp.setForeground(new java.awt.Color(0, 0, 0));
        Emp_iduepp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Emp_iduepp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        Emp_iduepp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_idueppActionPerformed(evt);
            }
        });
        jPanel2.add(Emp_iduepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 30));

        addressuepp.setBackground(new java.awt.Color(255, 255, 255));
        addressuepp.setColumns(10);
        addressuepp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addressuepp.setForeground(new java.awt.Color(0, 0, 0));
        addressuepp.setRows(5);
        addressuepp.setText("Address");
        addressuepp.setBorder(null);
        addressuepp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        addressuepp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressueppFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressueppFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(addressuepp);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 550, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 610, 450));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Welcome !");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 290, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update-business-user.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 420, 310));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("EMPLOYEE");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 410, 50));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("UPDATE");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 410, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Update Employee !");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, -1));

        serchuepp.setBackground(new java.awt.Color(255, 255, 255));
        serchuepp.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        serchuepp.setForeground(new java.awt.Color(128, 128, 128));
        serchuepp.setText("Serch Employee by Employee ID");
        serchuepp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 68, 187)));
        serchuepp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                serchueppFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                serchueppFocusLost(evt);
            }
        });
        jPanel3.add(serchuepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, 30));

        fName1uepp.setFont(new java.awt.Font("Consolas", 1, 21)); // NOI18N
        fName1uepp.setForeground(new java.awt.Color(128, 128, 128));
        fName1uepp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fName1uepp.setText("Serch Employee by Employee ID");
        jPanel3.add(fName1uepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 390, 30));

        jLabel2uepp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/magnifying-glass.png"))); // NOI18N
        jLabel2uepp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 68, 187)));
        jLabel2uepp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2ueppMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2uepp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 46, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 610, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void updateuepp(){
       
       try {
        
             //Data fetch from database
            String sql = "Select * From emp Where emp_id = '"+Eppuepp+"'";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
          //  ps.setString(1,"ERP_E1002");
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String emp_id =rs.getString("emp_id");
                String f_name =rs.getString("emp_fname");
                // System.out.println("EMpppppp "+f_name);
                String l_name =rs.getString("emp_lname");
                // System.out.println("pppnnn "+l_name);
                String Phone =rs.getString("emp_phone");
                 
                String Email =rs.getString("emp_email");
               // System.out.println("emlllll "+l_name);
                String Address =rs.getString("emp_address");
                
                firstnameuepp.setText(f_name);
                
                lastnameuepp.setText(l_name);
                
                phone3uepp.setText(Phone);
                  Emp_iduepp.setText(emp_id);
                emailuepp.setText(Email);
               addressuepp.setText(Address);
                
                
               // JOptionPane.showMessageDialog(this, "Product Found");
                
               
                rs.close();
                ps.close();
            }else{
               new Warning("Enter Correct Employee Id").setVisible(true);
               // System.out.println("Enter Correct Employee Id");
            }
        }catch(Exception e){
            System.out.println("error"+e);
        }
           
    }
    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        String fName = firstnameuepp.getText();
        String lName = lastnameuepp.getText();
        String ph = phone3uepp.getText();
        String mail = emailuepp.getText();

        String add = addressuepp.getText();
        String empp= Emp_iduepp.getText();

        if(fName.equals("First Name")||lName.equals("Last Name")||ph.equals("Phone")||mail.equals("Email")||add.equals("Address")||fName.equals("")||lName.equals("")||ph.equals("")||mail.equals("")||add.equals("")){
            // JOptionPane.showMessageDialog(this, "");
            new Warning("Fill up all field first").setVisible(true);
        }else{

            int i=0;
            try{
                Connection con=DATABASE_CONNECTION.getConnection();
                PreparedStatement ps=con.prepareStatement("UPDATE `emp` SET `emp_fname`='"+fName+"',`emp_lname`='"+lName+"',`emp_phone`='"+ph+"',`emp_email`='"+mail+"',`emp_address`='"+add+"' where emp_id ='"+empp+"'");
                i=ps.executeUpdate();
                con.close();
            }catch(Exception e){
                System.out.println(e);
            }
            // System.out.println("!!!!!!!!!!!!!!!!!!!!!!!!!!"+i);

            if(i>0){
                Succes su=new Succes();
                su.ot("Employee Profile Update Sucessfully ");
                su.setVisible(true);

                // JOptionPane.showMessageDialog(this, "Employee Profile Update Sucessfully ");

            }else{
                new Error("Please Try Again").setVisible(true);
                // JOptionPane.showMessageDialog(this, "Employee Profile Not Update Sucessfully");
            }
        }

    }//GEN-LAST:event_jLabel28MouseClicked

    private void firstnameueppFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameueppFocusGained
        // TODO add your handling code here:
        if(firstnameuepp.getText().equals("First Name")){
            fNameuepp.setVisible(true);
            firstnameuepp.setText("");
            firstnameuepp.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_firstnameueppFocusGained

    private void firstnameueppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameueppFocusLost
        // TODO add your handling code here:
        if(firstnameuepp.getText().equals("")){
            fNameuepp.setVisible(false);
            firstnameuepp.setText("First Name");
            firstnameuepp.setForeground(new Color(128,128,128));
        }else{
            fNameuepp.setVisible(true);
        }
    }//GEN-LAST:event_firstnameueppFocusLost

    private void lastnameueppFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameueppFocusGained
        // TODO add your handling code here:
        if(lastnameuepp.getText().equals("Last Name")){
            L_nameuepp.setVisible(true);
            lastnameuepp.setText("");
            lastnameuepp.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lastnameueppFocusGained

    private void lastnameueppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameueppFocusLost
        // TODO add your handling code here:
        if(lastnameuepp.getText().equals("")){
            L_nameuepp.setVisible(false);
            lastnameuepp.setText("Last Name");
            lastnameuepp.setForeground(new Color(128,128,128));
        }else{
            L_nameuepp.setVisible(true);
        }
    }//GEN-LAST:event_lastnameueppFocusLost

    private void lastnameueppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameueppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameueppActionPerformed

    private void emailueppFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailueppFocusGained
        // TODO add your handling code here:
        if(emailuepp.getText().equals("Email")){
            Emailuepp.setVisible(true);
            emailuepp.setText("");
            emailuepp.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_emailueppFocusGained

    private void emailueppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailueppFocusLost
        // TODO add your handling code here:
        if(emailuepp.getText().equals("")){
            Emailuepp.setVisible(false);
            emailuepp.setText("Email");
            emailuepp.setForeground(new Color(128,128,128));
        }else{
            Emailuepp.setVisible(true);
        }
    }//GEN-LAST:event_emailueppFocusLost

    private void phone3ueppFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3ueppFocusGained
        // TODO add your handling code here:
        if(phone3uepp.getText().equals("Phone")){
            Phoneuepp.setVisible(true);
            phone3uepp.setText("");
            phone3uepp.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_phone3ueppFocusGained

    private void phone3ueppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3ueppFocusLost
        // TODO add your handling code here:
        if(phone3uepp.getText().equals("")){
            Phoneuepp.setVisible(false);
            phone3uepp.setText("Phone");
            phone3uepp.setForeground(new Color(128,128,128));
        }else{
            Phoneuepp.setVisible(true);
        }
    }//GEN-LAST:event_phone3ueppFocusLost

    private void Emp_idueppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_idueppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_idueppActionPerformed

    private void addressueppFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressueppFocusGained
        // TODO add your handling code here:
        if(addressuepp.getText().equals("Address")){
            aaaauepp.setVisible(true);
            addressuepp.setText("");
            addressuepp.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_addressueppFocusGained

    private void addressueppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressueppFocusLost
        // TODO add your handling code here:
         if(addressuepp.getText().equals("")){
            aaaauepp.setVisible(false);
            addressuepp.setText("Phone");
           addressuepp.setForeground(new Color(128,128,128));
        }else{
            aaaauepp.setVisible(true);
        }
    }//GEN-LAST:event_addressueppFocusLost

    private void serchueppFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_serchueppFocusGained
         if(serchuepp.getText().equals("Serch Employee by Employee ID")){
            fName1uepp.setVisible(true);
            serchuepp.setText("");
            serchuepp.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_serchueppFocusGained

    private void serchueppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_serchueppFocusLost
        // TODO add your handling code here:
          if(serchuepp.getText().equals("")){
            fName1uepp.setVisible(false);
            serchuepp.setText("Serch Employee by Employee ID");
            serchuepp.setForeground(new Color(128,128,128));
        }else{
            fName1uepp.setVisible(true);
        }
    }//GEN-LAST:event_serchueppFocusLost

    private void jLabel2ueppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2ueppMouseClicked
        // TODO add your handling code here:
        
         String em_id = serchuepp.getText();
      try {
        
             //Data fetch from database
            String sql = "Select * From emp Where emp_id = '"+em_id+"'";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
          //  ps.setString(1,"ERP_E1002");
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String emp_id =rs.getString("emp_id");
                String f_name =rs.getString("emp_fname");
                // System.out.println("EMpppppp "+f_name);
                String l_name =rs.getString("emp_lname");
                // System.out.println("pppnnn "+l_name);
                String Phone =rs.getString("emp_phone");
                 
                String Email =rs.getString("emp_email");
               // System.out.println("emlllll "+l_name);
                String Address =rs.getString("emp_address");
                
                firstnameuepp.setText(f_name);
                
                lastnameuepp.setText(l_name);
                
                phone3uepp.setText(Phone);
                  Emp_iduepp.setText(emp_id);
                emailuepp.setText(Email);
               addressuepp.setText(Address);
                
                
               // JOptionPane.showMessageDialog(this, "Product Found");
                
               
                rs.close();
                ps.close();
            }else{
               new Warning("Enter Correct Employee Id").setVisible(true);
               // System.out.println("Enter Correct Employee Id");
            }
        }catch(Exception e){
            System.out.println("error"+e);
        }          
    }//GEN-LAST:event_jLabel2ueppMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Emailuepp;
    private javax.swing.JTextField Emp_iduepp;
    private javax.swing.JLabel L_nameuepp;
    private javax.swing.JLabel Phoneuepp;
    private javax.swing.JLabel aaaauepp;
    private javax.swing.JTextArea addressuepp;
    private javax.swing.JPanel crt_emp;
    private javax.swing.JTextField emailuepp;
    private javax.swing.JLabel fName1uepp;
    private javax.swing.JLabel fNameuepp;
    private javax.swing.JTextField firstnameuepp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel2uepp;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnameuepp;
    private javax.swing.JTextField phone3uepp;
    private javax.swing.JTextField serchuepp;
    // End of variables declaration//GEN-END:variables
}
